### ISSUE TITLE
Cannot find repo in HACS?

### ISSUE THREAD

**Issue by askpet** [kpoppel/homeassistant-novafos#7]
Hi,

I have tried to search for the repo - novafos. But it is not there.

Home Assistant Community Store
Integrationsversion:	1.26.2
Frontend-version:	20220714083628
Repositories:	1083

Home Assistant 2022.7.0
Brugerfladeversion: 20220706.0 - latest

**Comment by kpoppel** [comment]
That is because the integration is not published on the HACS list (I haven't dared to to that).
So do this:
  In HACS Go -> integrations -> ... (upper right corner) -> custom integrations.
Add this repository:
![image](https://user-images.githubusercontent.com/4174578/184558017-aa5a5e7c-0c17-48e6-a5f0-92c2d0da51ca.png)

Then you should be able to find it when searching in the HACS integration list.

I see this is not mentioned in the README, so I'd better fix that there as well.

**Comment by askpet** [comment]
Sorry for the late reply!

Thanks for the information. I installed it the manual way, but I think I am missing something. It does not show latest hour or usage today. I will go thrugh the documentation - since I might have missed something.
But this is SOOOO cool :-).

Will close this.

**Comment by kpoppel** [comment]
I am in progress with adding this to HACS default, so it can just be found without adding the repo manually.  Your issue pushed me the last 10cm :-)

As for data retrieval you will not see any until the next day because data is delayed in the datahub.  In the attributes you should see the last date data from the hub was valid.  So give it a few days and data should appear over time.
